# DonorsChoose.org Application Screening
- https://www.kaggle.com/c/donorschoose-application-screening

In [2]:
import pandas as pd
DATA_DIR = "data-temp"

In [3]:
train_data =  pd.read_csv(DATA_DIR + "/train.csv", low_memory=False)

In [7]:
train_data['teacher_id2'] = pd.factorize(train_data['teacher_id'])[0]

In [16]:
train_data.groupby(['teacher_id2']).agg('count')

,id,teacher_id,teacher_prefix,school_state,project_submitted_datetime,project_grade_category,project_subject_categories,project_subject_subcategories,project_title,project_essay_1,project_essay_2,project_essay_3,project_essay_4,project_resource_summary,teacher_number_of_previously_posted_projects,project_is_approved
teacher_id2,,,,,,,,,,,,,,,,
0,10,10,10,10,10,10,10,10,10,10,10,0,0,10,10,10
1,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1
2,4,4,4,4,4,4,4,4,4,4,4,0,0,4,4,4
3,16,16,16,16,16,16,16,16,16,16,16,0,0,16,16,16
4,10,10,10,10,10,10,10,10,10,10,10,0,0,10,10,10
5,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
6,2,2,2,2,2,2,2,2,2,2,2,0,0,2,2,2
7,2,2,2,2,2,2,2,2,2,2,2,0,0,2,2,2
8,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
9,4,4,4,4,4,4,4,4,4,4,4,0,0,4,4,4
10,4,4,4,4,4,4,4,4,4,4,4,0,0,4,4,4
11,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1
12,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1
13,2,2,2,2,2,2,2,2,2,2,2,0,0,2,2,2
14,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1
15,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
16,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1
17,18,18,18,18,18,18,18,18,18,18,18,0,0,18,18,18
18,8,8,8,8,8,8,8,8,8,8,8,1,1,8,8,8
19,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
20,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1
21,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1
22,5,5,5,5,5,5,5,5,5,5,5,0,0,5,5,5
23,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
24,5,5,5,5,5,5,5,5,5,5,5,0,0,5,5,5
25,19,19,19,19,19,19,19,19,19,19,19,0,0,19,19,19
26,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1
27,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1
28,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1
29,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104384,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1
104385,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1
104386,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1
104387,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1
104388,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1
104389,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1
104390,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1
104391,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1
104392,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1
104393,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1
104394,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1
104395,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1
104396,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1
104397,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1
104398,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1
104399,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1
104400,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1
104401,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1
104402,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1
104403,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1
104404,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1
104405,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1
104406,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
104407,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1
104408,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1
104409,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1
104410,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1
104411,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1
104412,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1
104413,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1